name: kde
bandwidth: 0.5
parent_bandwidth: 0.5
max_points: 2000
fit:
  epochs: 50
  batch_size: 4096
  lr: 1e-3
  weight_decay: 0.0
update:
  n_steps: 1
  batch_size: 4096
  lr: 1e-3
  weight_decay: 0.0
